<a href="https://colab.research.google.com/github/shaswath-29/EDA_LABORATORY_ASSIGNMENT/blob/Exp4_28.07.2026/missingvalues2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import pandas as pd;
import numpy as np;
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['chaitanya', 'hasith', 'praneeth',
'alex', 'adam'], columns=['CN', 'DBMS', 'EDA'])
dfx

           CN  DBMS  EDA
chaitanya  15    16   17
hasith     18    19   20
praneeth   21    22   23
alex       24    25   26
adam       27    28   29

In [ ]:
dfx['PROB'] = np.nan
dfx.loc['shaswath'] = np.arange(15, 19)
dfx.loc['wasim'] = np.nan
dfx['PROB'] = np.nan
dfx.loc['chaitanya', 'HSM'] = 20.
dfx

             CN  DBMS   EDA  PROB   HSM
chaitanya  15.0  16.0  17.0   NaN  20.0
hasith     18.0  19.0  20.0   NaN   NaN
praneeth   21.0  22.0  23.0   NaN   NaN
alex       24.0  25.0  26.0   NaN   NaN
adam       27.0  28.0  29.0   NaN   NaN
shaswath   15.0  16.0  17.0   NaN   NaN
wasim       NaN   NaN   NaN   NaN   NaN

In [ ]:
print(dfx.isnull())
print("notnull()")
print(dfx.notnull())
print("NaNs per column")
print(dfx.isnull().sum())
print("Total missing values in DataFrame")
print(dfx.isnull().sum().sum())
print("Count of reported values")
print(dfx.count())

              CN   DBMS    EDA  PROB    HSM
chaitanya  False  False  False  True  False
hasith     False  False  False  True   True
praneeth   False  False  False  True   True
alex       False  False  False  True   True
adam       False  False  False  True   True
shaswath   False  False  False  True   True
wasim       True   True   True  True   True
notnull()
              CN   DBMS    EDA   PROB    HSM
chaitanya   True   True   True  False   True
hasith      True   True   True  False  False
praneeth    True   True   True  False  False
alex        True   True   True  False  False
adam        True   True   True  False  False
shaswath    True   True   True  False  False
wasim      False  False  False  False  False
NaNs per column
CN      1
DBMS    1
EDA     1
PROB    7
HSM     6
dtype: int64
Total missing values in DataFrame
16
Count of reported values
CN      6
DBMS    6
EDA     6
PROB    0
HSM     1
dtype: int64

In [ ]:
print("Valid values in HSM")
print(dfx.HSM[dfx.HSM.notnull()])
print("HSM series after dropna()")
print(dfx.HSM.dropna())
print("dfx.dropna() (drops rows with any NaN)")
print(dfx.dropna())
print("dfx.dropna(how='all')")
print(dfx.dropna(how='all'))
print("dfx.dropna(how='all', axis=1)")
print(dfx.dropna(how='all', axis=1))
print("dfx.dropna(thresh=10, axis=1)")
print(dfx.dropna(thresh=10, axis=1))

Valid values in HSM
chaitanya    20.0
Name: HSM, dtype: float64
HSM series after dropna()
chaitanya    20.0
Name: HSM, dtype: float64
dfx.dropna() (drops rows with any NaN)
Empty DataFrame
Columns: [CN, DBMS, EDA, PROB, HSM]
Index: []
dfx.dropna(how='all')
             CN  DBMS   EDA  PROB   HSM
chaitanya  15.0  16.0  17.0   NaN  20.0
hasith     18.0  19.0  20.0   NaN   NaN
praneeth   21.0  22.0  23.0   NaN   NaN
alex       24.0  25.0  26.0   NaN   NaN
adam       27.0  28.0  29.0   NaN   NaN
shaswath   15.0  16.0  17.0   NaN   NaN
dfx.dropna(how='all', axis=1)
             CN  DBMS   EDA   HSM
chaitanya  15.0  16.0  17.0  20.0
hasith     18.0  19.0  20.0   NaN
praneeth   21.0  22.0  23.0   NaN
alex       24.0  25.0  26.0   NaN
adam       27.0  28.0  29.0   NaN
shaswath   15.0  16.0  17.0   NaN
wasim       NaN   NaN   NaN   NaN
dfx.dropna(thresh=10, axis=1)
Empty DataFrame
Columns: []
Index: [chaitanya, hasith, praneeth, alex, adam, shaswath, wasim]

In [ ]:
ar1 = np.array([85, 90, np.nan, 95])
ser1 = pd.Series(ar1)
print("NumPy Mean (returns NaN):", ar1.mean())
print("Pandas Mean (ignores NaN):", ser1.mean())
ser2 = dfx.HSM
print("Total HSM score (sum)")
print(ser2.sum())
print("Average HSM score (mean)")
print(ser2.mean())
print("Cumulative sum of HSM scores")
print(ser2.cumsum())

NumPy Mean (returns NaN): nan
Pandas Mean (ignores NaN): 90.0
Total HSM score (sum)
20.0
Average HSM score (mean)
20.0
Cumulative sum of HSM scores
chaitanya    20.0
hasith        NaN
praneeth      NaN
alex          NaN
adam          NaN
shaswath      NaN
wasim         NaN
Name: HSM, dtype: float64

In [ ]:
filledDf = dfx.fillna(0)
print("DataFrame filled with 0")
print(filledDf)
print("Original Means")
print(dfx.mean())
print("Means After Filling with 0")
print(filledDf.mean())
print("Forward Fill (ffill) on HSM")
print(dfx.HSM.ffill())
print("Backward Fill (bfill) on HSM")
print(dfx.HSM.bfill())

DataFrame filled with 0
             CN  DBMS   EDA  PROB   HSM
chaitanya  15.0  16.0  17.0   0.0  20.0
hasith     18.0  19.0  20.0   0.0   0.0
praneeth   21.0  22.0  23.0   0.0   0.0
alex       24.0  25.0  26.0   0.0   0.0
adam       27.0  28.0  29.0   0.0   0.0
shaswath   15.0  16.0  17.0   0.0   0.0
wasim       0.0   0.0   0.0   0.0   0.0
Original Means
CN      20.0
DBMS    21.0
EDA     22.0
PROB     NaN
HSM     20.0
dtype: float64
Means After Filling with 0
CN      17.142857
DBMS    18.000000
EDA     18.857143
PROB     0.000000
HSM      2.857143
dtype: float64
Forward Fill (ffill) on HSM
chaitanya    20.0
hasith       20.0
praneeth     20.0
alex         20.0
adam         20.0
shaswath     20.0
wasim        20.0
Name: HSM, dtype: float64
Backward Fill (bfill) on HSM
chaitanya    20.0
hasith        NaN
praneeth      NaN
alex          NaN
adam          NaN
shaswath      NaN
wasim         NaN
Name: HSM, dtype: float64